### ISSUE TITLE
[DATA-RQ] MAVSA

### ISSUE THREAD

**Issue by marianosanchezmoreno** [alphacastio/connectors-main#18]
**What is the estimated difficulty of this data request?**
Easy

**What is the Source / Url of this Data**
https://www.mav-sa.com.ar/#

**What is the format of the data source** 
HTML table

**What is the name of the new datasets or datasets?**
There are 8 datasets, related to 4 HTML tables from the quoted source.
Those HTML tables have bottoms that determine what kind of segment it belongs to (except in the case the last table, "caucion pesos").
Don't include " - Totales Operados" in the dataset name

The naming rule is: Financial - Argentina - MAVSA - ASSET - SEGMENT- Daily. So, the 8 datasets will be:

Financial - Argentina - MAVSA - CPD ECHEQ - Avalado- Daily.
Financial - Argentina - MAVSA - CPD ECHEQ - Garant.- Daily.
Financial - Argentina - MAVSA - CPD ECHEQ - No Garant. - Daily.
Financial - Argentina - MAVSA - CPD ECHEQ - Warant - Daily.
Financial - Argentina - MAVSA - PAGARÉ - Avalado - Daily.
Financial - Argentina - MAVSA - PAGARÉ - No Garant. - Daily.
Financial - Argentina - MAVSA - FCE - No Garant. - Daily.
Financial - Argentina - MAVSA - Caucion Pesos - Daily.

![image](https://user-images.githubusercontent.com/94461952/142260427-e352cb23-25d4-4e99-8136-aa54a4bbaf7b.png)

![image](https://user-images.githubusercontent.com/94461952/142261728-f3689dfb-694e-4f2a-86b4-1c70bdcd1f97.png)

**In which repository will it be?**
Pending

**Which are the Entities of the new dataset**
[Date, Plazo]

**What data should be extracted?**

Extract the data from each corresponding HTML table. Add a column (as long as the table itself, format YYYY-MM-DD) at the beginning of the dataset, named "Date", which will be set as entity.

![image](https://user-images.githubusercontent.com/94461952/142263145-5ec5dbaf-626a-44d5-b014-c2505d35dddb.png)

Please, bear in mind that when uploading to the database, it has to be done without deleting existing content by using: 

deleteMissingFromDB = False

alphacast.datasets.dataset(datasetId).upload_data_from_df(df, 
                 deleteMissingFromDB = False, onConflictUpdateDB = True)

**Comment by eze2286** [comment]
Acabo de realizar el pull request con la solución. 
Muchas gracias.
Saludos.
