### ISSUE TITLE
Datos Abiertos del Ministerio de Desarrollo Productivo

### ISSUE THREAD

**Issue by MacarenaOrtt** [alphacastio/connectors-main#21]
**What is the estimated difficulty of this data request?**
Easy

**What is the Source / Url of this Data**
[Datos Abiertos del Ministerio de Desarrollo Productivo](https://datos.produccion.gob.ar/dataset/consumo-electrico-por-sectores-manufactureros)

**What is the format of the data source** 
CSV

**What is the name of the new datasets or datasets?**
Activity - Argentina - Min. de Desarrollo Productivo - Electricity Consumption by Manufacturing Sector

**In which repository will it be?**
[Argentina Macro Basics](https://www.alphacast.io/repositories/20)

**Which are the Entities of the new dataset**
[Date, country]

**What data should be extracted?**
Both csv files. Tha date column format and the variables names are showed below in the images.
 
![image](https://user-images.githubusercontent.com/94381642/142250268-c3964eba-10db-47fb-a33b-664fda7d7eb8.png)

![image](https://user-images.githubusercontent.com/94381642/142266068-c67aa664-9556-42fb-9aaa-f15bbd41bf28.png)

**IMPORTANT**: a column named 'country' should be added with the name of the respective country on the rows (Argentina in this case) so that this field is set as an entity of the dataset when uploading to Alphacast site.

**Comment by eze2286** [comment]
Buen día, agrego mas abajo el codigo con la resolución, una para la serie original y otro para la desestacionalizada. Tienen incorporado ambas la columna date en el formato indicado y la columna country con el nombre de Argentina. Aguardo el comentario si es correcto. Muchas gracias. Saludos.

**Consumo eléctrico serie original:**

`import pandas as pd
pd.options.display.float_format = '{:.2f}'.format

url = "https://datos.produccion.gob.ar/dataset/bf0da6da-4cb0-4362-a925-0bdd69cf1c61/resource/f476cffb-7121-4f03-8cda-e51523c034e0/download/consumo_electrico_sectores_manufactureros_original.csv"

consumo_electrico_original = pd.read_csv(url)
consumo_electrico_original["country"] = "Argentina"
consumo_electrico_original.rename(columns={"periodo":"date"}, inplace = True)
consumo_electrico_original["date"] = pd.to_datetime(consumo_electrico_original["date"])
`
**Consumo eléctrico serie desestacionalizada:**

`import pandas as pd
pd.options.display.float_format = '{:.2f}'.format

url = "https://datos.produccion.gob.ar/dataset/bf0da6da-4cb0-4362-a925-0bdd69cf1c61/resource/3e342577-a2c3-414c-8290-39656c325c62/download/consumo_electrico_sectores_manufactureros_desestacionalizado.csv"

consumo_electrico_desestacionalizado = pd.read_csv(url)
consumo_electrico_desestacionalizado["country"] = "Argentina"
consumo_electrico_desestacionalizado.rename(columns={"periodo":"date"}, inplace = True)
consumo_electrico_desestacionalizado["date"] = pd.to_datetime(consumo_electrico_desestacionalizado["date"])
`

**Comment by eze2286** [comment]
Adjunto adicionalmente en txt ambos códigos.

[consumoe_electrico_original.txt](https://github.com/alphacastio/connectors-main/files/7575804/consumoe_electrico_original.txt)
[consumoe_electrico_desestacionalizada.txt](https://github.com/alphacastio/connectors-main/files/7575805/consumoe_electrico_desestacionalizada.txt)

**Comment by eze2286** [comment]
En el notebook quedarían como las imágenes
![original](https://user-images.githubusercontent.com/69882938/142751431-bbd679f1-18cf-430e-a869-53213664a1fb.JPG)
![desestacionalizada](https://user-images.githubusercontent.com/69882938/142751433-d18bd1dc-eca6-484f-bb7f-5e004a20d6e7.JPG)
 adjuntas:

**Comment by lcohan** [comment]
Excelente! mañana revisamos el PR!

**Comment by eze2286** [comment]
Como comentario adicional les aviso que no incorporé la parte del script correspondiente a la subida de datos a Alphacast ya que en el enunciado del ISSUE habla de que debe estar incorporado al Repositorio Argentina Macro Basics, N°20, el cual no me permite crear datasets, pero dejo acá abajo el código que debería utilizarse en caso de tener los 2 DatasetId:

`from alphacast import Alphacast
with open ('ApiKey.csv', 'r') as API_key:
    API_key = API_key.readline().strip()
alphacast = Alphacast(API_key)

alphacast.datasets.create("Actividad-Argentina-Min.de Desarrollo Productivo-Consumo de electricidad por sector 
                                         manufacturero_serie-original", 20, "Argentina Macro Basics")

alphacast.datasets.create("Actividad-Argentina-Min.de Desarrollo Productivo-Consumo de electricidad por sector 
                                        manufacturero_serie-desestacionalizada", 20, "Argentina Macro Basics")

alphacast.datasets.dataset(DatasetId).initialize_columns(dateColumnName = "date", entitiesColumnNames=["country"],
                                                     dateFormat= "%Y-%m-%d")

alphacast.datasets.dataset(DatasetId).initialize_columns(dateColumnName = "date", entitiesColumnNames=["country"],
                                                    dateFormat= "%Y-%m-%d")

alphacast.datasets.dataset(DatsetId).upload_data_from_df (consumo_electrico_original, deleteMissingFromDB = False,                                                      onConflictUpdateDB = True, uploadIndex=False)

alphacast.datasets.dataset(DatsetId).upload_data_from_df (consumo_electrico_desestacionalizado, deleteMissingFromDB = False,  onConflictUpdateDB = True)`

**Comment by MacarenaOrtt** [comment]
Buenas tardes Ezequiel. Revisamos el código y esta bien, solo un par de comentarios a tener en cuenta:
- En este caso el issue pedía un único dataset, entonces se debe hacer un merge del dataset original y el desestacionalizado en uno solo y el script que origina el mismo debería ser único, por mas que se requieran distintos archivos para armarlo.
- En lo posible evitar utilizar urls fijas, ya que si desde la fuente llegaran a cambiar el nombre de la misma el código no funciona.
- Siempre que se trate con variables que vengan desestacionalizadas de origen, agregarle el sufijo “sa_orig” o alguna identificación a las variables para diferenciarlas de las originales cuando este en el mismo dataset (esto no estaba especificado en el issue y debería estarlo, pero para que lo tengas en cuenta para los próximos).

Saludos!

**Comment by eze2286** [comment]
Hola Macarena, como estas? gracias por la respuesta. Perfecto, si alginas cosas no las tenia del todo claras o me quedaban dudas y por eso quería mas que nada saber si hacia falta agregar o hacer algo mas. Voy a tomar en cuenta lo que me decís. En este caso puntual debería reenviarte el código nuevamente como decís o ya estaría esta vez? Mas que nada porque me aparece aprobado el pull requests pero el ISSUE está abierto. Gracias.

**Comment by MacarenaOrtt** [comment]
Hola Ezequiel. No en este caso no hace falta que me reenvíes el código porque eran cosas menores, ahora cierro el issue. Saludos!
