### ISSUE TITLE
PAR - BCP - PIB

### ISSUE THREAD

**Issue by MacarenaOrtt** [alphacastio/connectors-main#28]
**What is the estimated difficulty of this data request?**
Easy 

**What is the Source / Url of this Data**
[Banco Central del Paraguay](https://www.bcp.gov.py/indice-ipp-mensual-i371)

**What is the format of the data source** 
Excel 

**What is the name of the new datasets or datasets?**
(1) Activity - Paraguay - BCP - Gross Domestic Product - Supply Approach
(2) Activity - Paraguay - BCP - Gross Domestic Product - Expenditure Approach

**In which repository will it be?**
[Paraguay Macro Basics](https://www.alphacast.io/repositories/39)

**Which are the Entities of the new dataset**
[Date, country]

**What data should be extracted?**
Both datasets come from the same file indicated below. 

![image](https://user-images.githubusercontent.com/94380303/143281810-aa315222-6745-4700-87ce-47b505b40f0c.png)

FOR DATASET (1) take the information from sheet 1 (PIB oferta).
WARNING: Take only the information up to Column AB (only nominal data, not variations (%)).

![image](https://user-images.githubusercontent.com/94380303/143285156-572443b8-1072-4023-a416-511609705678.png)

FOR DATASET (2) take the information from sheet 2 (PIB gasto).
WARNING: Take only the information up to Column AB (only nominal data, not variations (%)).

![image](https://user-images.githubusercontent.com/94380303/143286373-67d82455-80e5-4481-a1a5-83611ac5f530.png)

**IMPORTANT:** 
- Data should be in format: YY-MM-DD. As the information is in quarters, the month should be the first of each quarter. Quarters should be renamed as: Q1 = 01 , Q2= 04 , Q3 = 07 , Q4 = 10.
- On each dataset add a column named "country" with the corresponding country (Paraguay).

**Comment by eze2286** [comment]
Buen día, quería pedir si me pueden asignar este ISSUE.
Muchas gracias.
Saludos.
