### ISSUE TITLE
[DATA-RQ] Bolsa de Cereales

### ISSUE THREAD

**Issue by MacarenaOrtt** [alphacastio/connectors-main#32]
**What is the estimated difficulty of this data request?**
Easy 

**What is the Source / Url of this Data**
[Bolsa de Cereales](https://www.bolsadecereales.com/datasets)

**What is the format of the data source** 
Excel

**What is the name of the new datasets or datasets?**
(2) Agriculture - Argentina - Bolsa de Cereales - Estado y Condición de Cultivos (ECC) - Trigo
(3) Agriculture - Argentina - Bolsa de Cereales - Estado y Condición de Cultivos (ECC) - Maíz
(4) Agriculture - Argentina - Bolsa de Cereales - Estado y Condición de Cultivos (ECC) - Soja
(5) Agriculture - Argentina - Bolsa de Cereales - Estado y Condición de Cultivos (ECC) - Girasol

**In which repository will it be?**
Bolsa de Cereales (1617)

**Which are the Entities of the new dataset**
[Date, Zona, Cultivo, Campaña, Semana]

**What data should be extracted?**

FOR DATASETS (2) TO (5):
![image](https://user-images.githubusercontent.com/94380303/143875312-37ef443b-fcef-4db4-85f9-defab8e9d35d.png)
![image](https://user-images.githubusercontent.com/94380303/143913222-a8f3b752-a810-40ac-90da-aa4634efd722.png)

**IMPORTANT:** Add a 'Date' column with format YY-MM-DD. When uploading the data with the Alphacast library set the fields 'Cultivo', 'Zona', 'Campaña' and 'Semana' as the entities of the dataset.

**Comment by eze2286** [comment]
Buen día, consulto si me pueden asignar este ISSUE?. Y también consultar como debe interpretarse la fecha en este caso para que no queden días repetidos, por ejemplo, para el caso de la foto de arriba del dataset de trigo, ya que hay una misma semana repetida 12 veces por cada zona y no figura el mes puntual ni el día? Sebe debe generar una fecha aleatoria solo para que tenga esa entidad y pueda subirse?.
Muchas gracias.
Saludos.

**Comment by MacarenaOrtt** [comment]
Buen dia Ezequiel. En el caso de este dataset que tiene muchas entities no hay problema si hay fechas repetidas, ya que por mas que la fecha sea la misma para varias observaciones, todas seran distintas porque estan los campos 'Campaña', 'Zona', y 'Semana' que las distinguen. En cuanto a como armar la variable 'Date', podes tomar el año de inicio de la campaña y el mes y dia podes armarlo en función del nro de semana dentro de ese periodo.
Saludos!
