### ISSUE TITLE
[DATA-RQ] MAE Volume

### ISSUE THREAD

**Issue by MacarenaOrtt** [alphacastio/connectors-main#35]
**What is the estimated difficulty of this data request?**
Easy

**What is the Source / Url of this Data**
https://www.mae.com.ar/mercado/estadisticas/volumen-negociado

**What is the format of the data source** 
HTML

**What is the name of the new datasets or datasets?**
![image](https://user-images.githubusercontent.com/94461952/143485627-c9dec3d3-2bdc-4aeb-9671-8e420882e5f6.png)

There are 3 datasets, related to 3 HTML tables from the quoted source. Dataset's names will be:

Financial - Argentina - MAE - Fixed-Income purchase/sale volume - Monthly
Financial - Argentina - MAE - Fixed-Income repo volume - Monthly
Financial - Argentina - MAE - FOREX volume - Monthly

**In which repository will it be?**
Pending

**Which are the Entities of the new dataset**
[Date, country]

**What data should be extracted?**
For each HTML table, extract the figure within the cells so that the output dataset is a two-column stacked table whose names are "Date" and "Volume". Besides, delete point as thousands separator.

![image](https://user-images.githubusercontent.com/94461952/143488577-ebf000ec-a3d2-4f26-b2be-953274f3014c.png)

**IMPORTANT:** Add a column named 'country' with the corresponding country (Argentina) on each dataset.

**Comment by eze2286** [comment]
Buen día Macarena!, ya envié el pull request con la resolución. Te pido si es posible me lo asignes.
Gracias.
Saludos!
