### ISSUE TITLE
[DATA-RQ] INDEC - ARG - BOP

### ISSUE THREAD

**Issue by MacarenaOrtt** [alphacastio/connectors-main#37]
**What is the estimated difficulty of this data request?**
Easy

**What is the Source / Url of this Data**
[INDEC](https://www.indec.gob.ar/indec/web/Nivel4-Tema-3-2-41)

**What is the format of the data source** 
Excel 

**What is the name of the new datasets or datasets?**
BOP - Argentina - INDEC - Price & Quantities of External Trade

**In which repository will it be?**
[Argentina - INDEC](https://www.alphacast.io/repositories/18)

**Which are the Entities of the new dataset**
[Date, country]

**What data should be extracted?**
![image](https://user-images.githubusercontent.com/94380303/144303801-7bdb21be-d5cd-4da6-81ea-973a7977e8ab.png)
IMPORTANT: Name the variables related to imports as follows: "M-CATEGORÍA-VARIABLE". For Example "M - Bienes de Capital - Valor"
![image](https://user-images.githubusercontent.com/94380303/144307517-d9d1b30a-ad84-4116-acb9-d0314e751d98.png)
IMPORTANT: Name the variables related to exports as follows: "X-RUBRO-VARIABLE". For Example "X - Productos Primarios - Valor"
![image](https://user-images.githubusercontent.com/94380303/144308776-cb3ecd06-98f0-47a3-88ef-42ad52ce8f6f.png)

**IMPORTANT:**
- The 'Date' column should be in format YY-MM-DD.
- Add a 'country' column with the corresponding country (Argentina).

**Comment by eze2286** [comment]
Buen día Macarena!. Te pido si es posible me asignes este ISSUE. Gracias!. Saludos!

**Comment by eze2286** [comment]
Y una consulta, en este caso, no se puede obtener directamente el enlace de forma dinámica ya que el contenido de la web se actualiza dinámicamente mediante un script de java, intenté con Selenium pero no me lo detecta. La consulta es si directamente se puede utilizar para parserlo el enlace de acceso que figura en la web:"https://www.indec.gob.ar/ftp/cuadros/economia/serie_mensual_indices_expo.xls"? o hay alguna otra alternativa?

Aguardo la respuesta.
Muchas gracias.
Saludos.

**Comment by eze2286** [comment]
Hola Macarena, ya pude resolver el tema de la obtención de forma dinámica de los enlaces que consulté en el comentario anterior. Así que solo te pido si me lo asignas en caso de ser posible. 
Gracias.
Saludos.
