### ISSUE TITLE
[DATA-RQ] BCU - URU

### ISSUE THREAD

**Issue by MacarenaOrtt** [alphacastio/connectors-main#39]
**What is the estimated difficulty of this data request?**
Easy

**What is the Source / Url of this Data**
[BCU](https://www.bcu.gub.uy/Estadisticas-e-Indicadores/Paginas/Series-Estadisticas-del-PIB-por-industrias.aspx)

**What is the format of the data source** 
Excel 

**What is the name of the new datasets or datasets?**
Activity - Uruguay - BCU - Physical Volume Index

**In which repository will it be?**
[Uruguay Macro Basics](https://www.alphacast.io/repositories/46)

**Which are the Entities of the new dataset**
[Date, Country]

**What data should be extracted?**

![image](https://user-images.githubusercontent.com/94381642/146952474-9ebc94c1-9456-453a-b2a1-f4f7c54ab25f.png)

![image](https://user-images.githubusercontent.com/94381642/146953867-36acb5ab-de3f-46c6-9f46-58d50559af3c.png)

**IMPORTANT:**
- The 'Date' column should be in format YY-MM-DD. As the information is in quarters, the month should be the first of each quarter. Quarters should be renamed as: I = 01 , II= 04 , III = 07 , IV = 10.
- Add a 'country' column with the corresponding country (Uruguay).

**Comment by eze2286** [comment]
Buen día Macarena, como estás?
Quería pedirte si podes asignarme este ISSUE?
Por otro lado consultarte si el resto de los ISSUE que hice pull requests hace ya un tiempo, todavía no fueron analizados o es que no están correctos y hay que hacer modificaciones?

Muchas gracias.
Saludos!

**Comment by MacarenaOrtt** [comment]
Hola Ezequiel, como estas?
Primero perdón por la demora en la respuesta, ya esta aprobado el pull request de ese issue. Los anteriores todavía estan pendientes de revisar, nos vamos a ir poniendo al día en estos días. Si no estan correctos o hubiera que modificarlos te vamos a avisar por este medio.

Saludos!
