### ISSUE TITLE
[DATA-RQ] USA Monthly GDP Index

### ISSUE THREAD

**Issue by MacarenaOrtt** [alphacastio/connectors-main#42]
**What is the estimated difficulty of this data request?**
Easy

**What is the Source / Url of this Data**
The data comes from the [IHS Markit Website ](https://ihsmarkit.com/products/us-monthly-gdp-index.html)

**What is the format of the data source** 
Excel

**What is the name of the new datasets or datasets?**
Activity - USA - IHS Markit - Monthly GDP Estimate

**In which repository will it be?**
[USA Macro Basics](https://www.alphacast.io/repositories/47)

**Which are the Entities of the new dataset**
[Date, country]

**What data should be extracted?**
<img width="641" alt="image" src="https://user-images.githubusercontent.com/94558837/148239563-02b10b88-35ff-424e-82aa-646fb1731ce4.png">
In the website, click on the "Monthly GDP Index: Historical Data" link. It will download an Excel file containing all of the relevant data.

<img width="266" alt="image" src="https://user-images.githubusercontent.com/94558837/148239501-61683c01-bcce-49eb-8f44-56af554c3f34.png">
The Excel file has three sheets, only one of which is relevant: "Data". Index and Commentary can be disregarded. 

<img width="166" alt="image" src="https://user-images.githubusercontent.com/94558837/148239356-d08ccbaf-ffab-4de4-b0cc-02d1e1a712c3.png">
To translate into a dataset, create two columns: one, labeled "Date", will have the monthly date, starting January 1992 and ending at the final month available. It has to be created in YYYY-MM-DD format. The second column will be labeled "country", and will say "United States" for every value. 

Both of the columns containing data are relevant. They can keep the current names "Monthly Nominal GDP" and "Monthly Real GDP".

**Comment by eze2286** [comment]
Hola Macarena, como estas?. Me podrías asignar este ISSUE?.
Gracias.
Saludos.
