### ISSUE TITLE
[DATA-RQ] IDB - Prices

### ISSUE THREAD

**Issue by MacarenaOrtt** [alphacastio/connectors-main#43]
**What is the estimated difficulty of this data request?**
Easy

**What is the Source / Url of this Data**
[Inter-American Development Bank](https://data.iadb.org/DataCatalog/Dataset)

**What is the format of the data source** 
Excel or CSV

**What is the name of the new datasets or datasets?**
(1) Prices - Global - IDB - Consumer Price Index
(2) Prices - Global - IDB - Export Prices Index
(3) Prices - Global - IDB - Import Prices Index
(4) Prices - Global - IDB - Wholesale Price Index

**In which repository will it be?**
Pending

**Which are the Entities of the new dataset**
[Date, Country]

**What data should be extracted?**
FOR DATASETS (1) TO (4):
![image](https://user-images.githubusercontent.com/94380303/145086356-753cd326-9d44-4c28-a733-108cc0b78da5.png)
![image](https://user-images.githubusercontent.com/94380303/145092101-d40d3d7e-ecd0-4562-8e72-20275cac400b.png)

IMPORTANT: 
- For all indicators download only the index value (no transformations). 
- Remove the suffix "index" from the variable names.
- The indicators group and the indicator selected for each dataset will be the following:
 
(1) Indicators group: CPI, Indicator: CPI: index
(2) Indicators group: Export Prices, Indicator: Export Prices: index
(3) Indicators group: Import Prices, Indicator: Import Prices: index
(4) Indicators group: WPI, Indicator: WPI: index

**Comment by eze2286** [comment]
Buenas tardes Macarena, una consulta respecto a este ISSUE. Veo que el acceso mediante código a los archivos solicitados excels o CSV no tienen un link href por el cual acceder a ellos, entonces estoy pensando que la solución podría ser acceder mediante código, de forma automatizada, a la descarga de los mismos y luego trabajar las transformaciones y carga correspondiente desde los archivos descargados en la carpeta de descargas. Quería consultarte si esta opción es viable?
Muchas gracias.
Saludos.

**Comment by eze2286** [comment]
Hola Macarena, Me olvidé de pedirte que en caso de ser viable lo que te comenté, si es posible me lo asignes.
Gracias.
Saludos.

**Comment by MacarenaOrtt** [comment]
Hola Ezequiel, como va?
Disculpá por la demora en la respuesta, este issue finalmente ya lo tenemos resuelto de forma interna en el equipo, asi que ahora lo voy a cerrar.
Saludos!
